wassuphealth/urls.py
from django.conf.urls 					import patterns, include, url
from django.contrib 					import admin
from django.conf.urls.static            import static
from portal 							import views
from django.contrib.staticfiles.urls    import staticfiles_urlpatterns
from postman_attachments.forms          import FullReplyAttachmentForm, FullWriteAttachmentForm
from postman.views                      import *

#wires of the site
urlpatterns = patterns('',
    # Examples:

    # Django-Admin
    url(r'^admin/', include(admin.site.urls), name='django_admin'),

    # Forums - landing and main
    url(r'^forums/$','forums.views.forum_pre_landing', name='view_forums'),
    url(r'^forums/index/$', 'forums.views.main', name='forums'),

    # Community Forums
	url(r'^forums/community/(\d+)/$', 'forums.views.forum', name='forum'),
    url(r'^forums/community/thread/(\d+)/$', 'forums.views.show_thread', name='thread'),
    url(r'^forums/community/reply/(\d+)/$', 'forums.views.reply_to_thread', name='reply'),
    url(r'^forums/community/new_thread/(\d+)/$', 'forums.views.new_thread', name='new_thread'),
    url(r'^forums/community/post/(upvote|downvote)/(\d+)/(\d+)/$', 'forums.views.post_vote', name='post_vote'),

    # Doctors Forums
    url(r'^forums/doc/(\d+)/$', 'QnA.views.show_specialty', name='questions_specialty'),
    url(r'^forums/doc/question/get/(\d+)/$', 'QnA.views.show_specialty_question', name='get_question'),
    url(r'^forums/doc/question/(upvote|downvote)/(\d+)/$', 'QnA.views.question_vote', name='question_vote'),
    url(r'^forums/doc/question/save/(\d+)/$', 'QnA.views.new_question', name='save_question'),
    url(r'^forums/doc/question/answer/save/(\d+)/$', 'QnA.views.save_answer', name='save_answer'),

    # Portal
	url(r'^$','portal.views.home', name='home'),
    url(r'^news/$','portal.views.news', name='news'),
    url(r'^tag/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_tagged_under', name='view_tagged'),
    url(r'^tags/$', 'portal.views.view_all_tags', name='view_all_tags'),
	url(r'^mastercategory/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_master_category', name='view_master_category'),
    url(r'^category/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_category', name='view_category'),
    url(r'^article/(?P<id>\d+)/(?P<slug>[^\.]+)', 'portal.views.view_article', name='view_article'),
    url(r'^conditions/$', 'portal.views.view_all_conditions', name='conditions'),
    url(r'^conditions/view/(?P<id>\d+)/(?P<slug>[^\.]+)', 'portal.views.view_condition', name='view_condition'),

 	# Registration
    url(r'^register/$','registration.views.index', name='registration'),
    url(r'^register/public/$', 'registration.views.register_publicuser', name='publicuser_registration'),
    url(r'^register/clinician/$', 'registration.views.register_clinician', name='clinician_registration'),
    url(r'^register/confirm/(?P<activation_key>\w+)/', 'registration.views.register_confirm'),
    url(r'^account-activated/$','registration.views.account_activated', name='account-activated'),
    url(r'^activation-timeout/$','registration.views.account_timeout', name='account-timeout'),

    # User Authentication
    url(r'^login/$', 'authentication.views.portal_login', name='portal_login'),
    url(r'^login-account/$', 'authentication.views.user_login', name='login'),
	url(r'^logout-account/$', 'authentication.views.user_logout', name='logout'),
    url(r'^account-inactive/$','authentication.views.account_inactive', name='account-inactive'),

    # dashboard
    url(r'^dashboard/$', 'dashboard.views.index', name='dashboard_index'),
    url(r'^dashboard/account/$', 'dashboard.views.edit_profile', name='profile'),
    url(r'^dashboard/healthinfo/$', 'dashboard.views.edit_healthinfo', name='healthinfo'),
    url(r'^dashboard/activities/$', 'dashboard.views.view_user_activities', name='view_activities'),
    url(r'^dashboard/questions/all/$', 'dashboard.views.view_all_activities', name='view_all_activities'),
    url(r'^dashboard/askadoc/save/$', 'dashboard.views.askadoc_save', name='save_doc_form'),
    url(r'^dashboard/commforums/save/$', 'dashboard.views.commforums_save', name='save_comm_form'),
    url(r'^dashboard/professionalinfo/$', 'dashboard.views.edit_clinicianinfo', name='clinicianinfo'),
    url(r'^dashboard/profile/upload/$', 'dashboard.views.profile_avatar_upload', name="profile_avatar"),
    url(r'^dashboard/feedback/$', 'dashboard.views.feedback', name='dfeedback'),
    url(r'^dashboard/feedback/submit/$', 'dashboard.views.submit_feedback', name='d_save_feedback'),
    url(r'^dashboard/appointments/edit/$', 'dashboard.views.edit_appointment', name='edit_appointment'),
    url(r'^dashboard/appointments/delete/$', 'dashboard.views.delete_appointment', name='delete_appointment'),
    url(r'^dashboard/appointments/all/$', 'dashboard.views.get_all_appointments', name='get_all_appointments'),
    url(r'^dashboard/appointments/view/(\d+)/$', 'dashboard.views.view_appointment', name='view_appointment'),

    # dashboard == postman

    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
        WriteView.as_view(form_class=FullWriteAttachmentForm),
        name='pm_write'),

    url(r'^reply/(?P<message_id>[\d]+)/$',
        ReplyView.as_view(form_class=FullReplyAttachmentForm),
        name='pm_reply'),

    url(r'^messages/',include('postman.urls')),

    # dashboard == avatar
    url(r'^avatar/', include('avatar.urls')),

    # comments
    url(r'^comments/', include('django_comments.urls')),

    # appointments
    url(r'^appointments/book/doctor/(\d+)/$', 'appointments.views.book_appointment', name='book_appointment'),
    url(r'^appointments/save/(\d+)/$', 'appointments.views.save_appointment', name='save_appointment'),

    # Profile
    url(r'^doctors/view/(\d+)/$', 'profile.views.view_doctor_profile', name='view_doctor'),
    url(r'^doctors/', 'profile.views.view_doctors', name='doc_dir'),

    # Feedback
    url(r'^feedback/$','feedback.views.index', name='feedback'),
    url(r'^feedback/submit/$','feedback.views.submit_feedback',name='save_feedback'),

    # Static Pages
    url(r'', include('django.contrib.flatpages.urls')),
    url(r'^PDPA/$', 'flatpage', {'url': '/PDPA/'}, name='PDPA'),
	url(r'^about-wassuphealth/$', 'flatpage', {'url': '/about-wassuphealth/'}, name='about-wassuphealth'),
    url(r'^legal/terms-of-use/$', 'flatpage', {'url': '/legal/terms-of-use'}, name='legal-terms-of-use'),
    url(r'^forums/disclaimer/$', 'flatpage', {'url': '/forums/disclaimer/'}, name='forums-disclaimer'),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        # Media Files
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
    )

profile/models.py
from django.db                  import models
from django.utils               import timezone
from django.utils.http          import urlquote
from django.utils.translation   import ugettext_lazy as _
from django.core.mail           import send_mail
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.conf                import settings

import datetime

class UserManager(BaseUserManager):

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    A fully featured User model with admin-compliant permissions that uses
    a full-length email field as the username.

    Email and password are required. Other fields are optional.
    """
    email       = models.EmailField('Email Address', max_length=254, unique=True, db_index=True)

    username    = models.CharField('User Name', max_length=30, unique=True)

    first_name  = models.CharField('First Name', max_length=30, blank=True)

    last_name   = models.CharField('Last Name', max_length=30, blank=True)

    initial     = models.CharField('Initial', max_length=4, blank=True)

    is_staff    = models.BooleanField('Staff status', default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))

    is_active   = models.BooleanField('Active', default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))

    is_admin    = models.BooleanField(default=False)

    date_joined = models.DateTimeField('Date joined', default=timezone.now)

    objects     = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])


class UserProfile(models.Model):

    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

    activation_key = models.CharField(max_length=40, blank=True)

    key_expires = models.DateTimeField(default=datetime.date.today())

    country = (
        ('SG','Singapore'),
        ('MY','Malaysia'),
        ('ID','Indonesia'),
        ('TH','Thailand'),
        ('IN','India'),
        ('VN','Vietnam'),
        ('KOR','South Korea, Republic of'),
        ('AU','Australia'),
        ('NZ','New Zealand'),
        ('PH','Philippines'),
        ('TW','Taiwan, Republic of China'),
        ('CN','China, People''s Republic of'),
        ('HK','Hong Kong SAR, China'),
        ('MAC','Macau SAR, China')
    )
    country = models.CharField(
        max_length = 4, choices = country, default='SG'
    )

    gender = (
        ('M', 'Female'),
        ('F', 'Male'),
        ('UN', 'Unknown'),
    )

    gender = models.CharField(
        max_length = 2, choices = gender, default='F'
    )

    # The additional attributes we wish to include.

    zip_code = models.CharField(
    	max_length = 6
    )

    birthday = models.DateTimeField(null=True)

    posts = models.IntegerField(default = 0)

    home_address = models.TextField()

    avatar = models.ImageField("Profile Pic", upload_to='avatars/', blank=True, null=True)

    mobile_no = models.CharField(
    	max_length = 20
    )


class Clinic(models.Model):

    # Clinic of Practice
    name = models.CharField('Clinic Name', max_length=254, unique=True)

    # Place of practice e.g. Family Care Clinic
    address = models.TextField()

    # Contact no. of practice
    contact_no = models.CharField(
        max_length = 20
    )

    # Country of practice
    country = models.CharField(
        max_length = 200
    )

    # Website URL of practice
    website = models.URLField('Business Website')

    # Business Email Address for Contact
    business_email_address = models.EmailField('Business Email Address', max_length=254, db_index=True)

    # Place of practice coordinates for use with Google Maps.
    gps_coord = models.CharField(
        max_length = 20
    )

    # Business Registration Date
    business_registered_date = models.DateTimeField('Business Registration Date', null=True)

    # Services in semi-colon delimited fashion
    services = models.TextField('Provided Services')

# User Model for Clinician - with some common features from the UserProfile class
class ClinicianProfile(models.Model):

    """
    - My Education (institutions)(from yyyy - yyyy) provide 3 rows and allow to add *Do It Later*
    - My Medical Training (hospital)(from yyyy - yyyy) provide 3 rows and allow to add *Do It Later*
    """

    userprofile = models.OneToOneField(UserProfile)

    clinic_of_practice = models.ForeignKey(Clinic, default=1)

    specialty_choices = (
        (1, 'Anaethesiology'),
        (2, 'Cardiology'),
        (3, 'Cardiothoracic Surgery'),
        (4, 'Colorectal Surgery'),
        (5, 'Dentistry'),
        (6, 'Dermatology'),
        (7, 'Endocrinology'),
        (8, 'ENT'),
        (9, 'Gastroenterology'),
        (10, 'General Surgery'),
        (11, 'Geriatrics'),
        (12, 'Gynaecology'),
        (13, 'Haematology'),
        (14, 'Hand Surgery'),
        (15, 'Infectious Disease'),
        (16, 'Internal Medicine'),
        (17, 'Oncology'),
        (18, 'Neonatology'),
        (19, 'Neurology'),
        (20, 'Obstetrics'),
        (21, 'Ophthalmology'),
        (22, 'Orthopaedic Surgery'),
        (23, 'Paediatric'),
        (24, 'Paediatric Surgery'),
        (25, 'Plastic Surgery'),
        (26, 'Psychiatry'),
        (27, 'Renal Medicine'),
        (28, 'Respiratory Medicine'),
        (29, 'Rheumatology'),
        (30, 'Urology')
    )

    medical_careergrade_choices = (
        (1, 'Medical Officer'),
        (2, 'Senior Medical Officer'),
        (3, 'Registrar'),
        (4, 'Associate Consultant'),
        (5, 'Consultant'),
        (6, 'Senior Consultant'),
        (7, 'Family Physician'),
        (8, 'Family Physician Associate Consultant'),
        (9, 'Family Physician Consultant'),
        (10, 'Family Physician Senior Consultant'),
        (11, 'Resident'),
        (12, 'Senior Resident'),
        (13, 'Principal Resident')
    )

    # Professional License
    # for SG: SMC MCR Number
    medical_reg_no = models.CharField(
        max_length = 9
    )

    registered_date = models.DateTimeField(null=True)

    clinical_specialty = models.IntegerField(choices = specialty_choices, default=1)

    medical_careergrade = models.IntegerField(choices = medical_careergrade_choices, default=1)

    # Graduate School
    grad_school = models.CharField(
        max_length = 200
    )

    grad_year = models.CharField(
        max_length = 4
    )

    degree_type = models.CharField(
        max_length = 7
    )

    years_of_practice = models.IntegerField(default=0)

    # Free Text Fields
    # text profile of clinician - about me
    medical_interests = models.TextField(default="")
    writeup_text = models.TextField(default="")
    medical_memberships = models.TextField(default="")
    publications = models.TextField(default="")
    affiliations = models.TextField(default="")
    awards = models.TextField(default="")

# User Model for User - with some common features from the UserProfile class
class PublicUserProfile(models.Model):

    #More to be added. E.g. various medical related data
    userprofile = models.OneToOneField(UserProfile)

    race = models.CharField(max_length=100, default="")

    sexual_history_options = ((1, 'Not Sexually Active'),(2, 'Homosexual'),(3, 'Heterosexual'),(4, 'Bisexual'))
    sexual_history = models.IntegerField(choices = sexual_history_options, default=1)

    current_medical_conditions = models.TextField(default="")

    lactose_intolerant_options = ((1,'Yes'),(2,'No'))
    lactose_intolerant = models.IntegerField(choices = lactose_intolerant_options, default=1)

    smoking_options = ((1,'Yes'),(2,'No'))
    smoking = models.IntegerField(choices = smoking_options, default=1)
    smoking_packs = models.CharField(max_length = 4, default=0)
    smoking_years = models.CharField(max_length = 4, default=0)

    alcohol_intake_options = ((1, 'None'),(2,'<7 drinks a week'),(3,'8-14 drinks a week'),(4,'>15 drinks a week'))
    alcohol_intake = models.IntegerField(choices = alcohol_intake_options, default=1)

base/templates/qna/doc_post.html
{% extends 'common/common_base.html' %}
{% block title %}
<a href="{% url 'forums' %}">Wassuphealth!
  <span class="sub">Forums</span>
</a>
{% endblock %}
{% block wsh_content %}

  {% load staticfiles %}
  {% load widget_tweaks %}

    <div class="container">
			<div class="hidden-xs hidden-sm" style="margin-top:100px;"></div>
			<div class="row col-md-12">
				<h1>Wassup Doc!<small> - {{ Question.question }} - for original author to follow up. Lifecycle of question: 10 weeks. Doctors post replies via dashboard. Question is under a specialty. Need another page to list the question under each category. Voting of question needed. Highest voted question will appear first.</small></h1>
        <p align="right"> <i><b>Posted on:</b> {{ Question.timestamp }}</p>
			</div>
			<div class="col-md-8 col-sm-12 container">
        {% if Answer %}

          {% for ans in Answer %}
            <div style="row">
					    <p class="{% cycle 'leftspeech' 'rightspeech' %} col-xs-12">
                {{ ans.answer }}
					    </p>
					    <div class="col-xs-2">
						    <img class="img-responsive img-circle" src="{% static 'assets/images/people/profile-s-1.png' %}" alt="" />
					    </div>
					    <div class="col-xs-10">
                {{ ans.answer_provided_by }}
					    </div>
				    </div>
          {% endfor %}

        {% else %}
          <h5>No answers yet. You will be the first!</h5>
        {% endif %}

			</div>
			<div class="col-md-4 col-sm-12 container">
				<div style="row">
					<form>
						<div class="form-group">
							<label for="voting" class="control-label">Ask a Question!</label>
							<button type="submit" class="btn btn-default pull-right">Submit!</button>
							<textarea class="form-control" rows="3"></textarea>
						</div>
					</form>
				</div>
				<div style="row">
					<div class="list-group">
						<p class="list-group-item list-group-item-warning">
								Related Specialist
						</p>
						<a href="#" class="list-group-item">Dapibus ac facilisis in</a>
						<a href="#" class="list-group-item">Morbi leo risus</a>
						<a href="#" class="list-group-item">Porta ac consectetur ac</a>
						<a href="#" class="list-group-item">Vestibulum at eros</a>
					</div>
				</div>
				<div style="row">
					<div class="list-group">
						<p class="list-group-item list-group-item-warning">
							List of Popular Topics
						</p>
						<a href="#" class="list-group-item">
						<h4 class="list-group-item-heading">I EAT TOO MUCH SUGER</h4>
						<p class="list-group-item-text">Like the title said, does that means i got diabetes?</p>
						</a>
						<a href="#" class="list-group-item">
						<h4 class="list-group-item-heading">I was kissed by ernest</h4>
						<p class="list-group-item-text">and now i'm dying.</p>
						</a>
					</div>
				</div>
			</div>
		</div>

{% endblock %}

base/templates/qna/doc_question_answers.html
{% extends 'common/common_base.html' %}
{% block title %}
<a href="{% url 'forums' %}">Wassuphealth!
  <span class="sub">Forums</span>
</a>
{% endblock %}
{% block wsh_content %}

  {% load staticfiles %}
  {% load widget_tweaks %}
  {% load avatar_tags %}

    <div class="container">
			<div class="hidden-xs hidden-sm" style="margin-top:100px;"></div>


      <div class="col-md-2 col-sm-12">
			</div>

			<div class="col-md-8 col-sm-12 container">

        <div class="row col-sm-12 col-md-12 container">
          <h2 align="left">
            <b>
            Question
            {% if Question.private %}
              <small><span class="glyphicon glyphicon-lock"></span></small>
            {% endif %}
            </b>
          </h2>
          <p align="justify" style="font-size:20px">{{ Question.question }}</p>
          <br/>
          <p align="right"><i>Posted by <b>{{ Question.posted_by.username }}</b> on <b>{{ Question.timestamp }}</b> under <b><a href="{% url 'questions_specialty' specialty_id %}">{{ specialty_title }}</a></b></i></p>
          {% if user.is_authenticated %}
            <p align=right>
            {% if user.userprofile.clinicianprofile and Question.tag_profile %}
              <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#healthprofile"><span class="glyphicon glyphicon-modal-window"></span> Click for user's profile</button>
            {% endif %}
            {% if Answer %}
              <a href="{% url 'question_vote' 'upvote' Question.pk %}"><button type="button" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-thumbs-up"></span> <b>This helps!</b> ({{ Question.upvote }})</button></a>
            {% endif %}
          {% else %}
            <p align=right><b>This helps!</b> ({{ Question.upvote }})</p>
          {% endif %}
        </div>

        {% if user.is_authenticated %}
          {% if user.userprofile.clinicianprofile and Question.tag_profile %}
          <div id="healthprofile" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">{{ Question.posted_by.username }}'s Health Profile</h4>
                </div>
                <div class="modal-body">
                  <p><b>Race:</b> {{ publicuserprofile.race }}</p>
                  <p><b>Height:</b> {{ publicuserprofile.height }}cm</p>
                  <p><b>Weight:</b> {{ publicuserprofile.weight }}KG</p>
                  <p><b>Allergies:</b> {{ publicuserprofile.allergies }}</p>
                  <p><b>Existing Medical Conditions:</b> {{ publicuserprofile.current_medical_conditions }}</p>
                  <p><b>Sexual History?</b> {{ publicuserprofile.get_sexual_history_display }}</p>
                  <p><b>Lactose Intolerant?</b> {{ publicuserprofile.get_lactose_intolerant_display }}</p>
                  <p><b>Smoking?</b> {{ publicuserprofile.get_smoking_display }}</p>
                  <p><b>Alcohol Intake?</b> {{ publicuserprofile.get_alcohol_intake_display }}</p>
                  <p><b>Relative with Cancer?</b> {{ publicuserprofile.get_relative_with_cancer_display }}</p>
                  <p><b>Which cancer?</b> {{ publicuserprofile.cancer_desc }}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

          </div>
        </div>
        {% endif %}
        {% endif %}

        <div style="row">
          <div class="col-sm-12 col-sm-12 container">
            <div class="form-group">
              {% if user.is_authenticated %}

                {% if user.userprofile.clinicianprofile or Question.posted_by.email = user.email and Question.status = 'ANSWERED'  %}
                <form action="{% url 'save_answer' question_id %}" method="POST">
                  {% csrf_token %}
                  <label for="voting" class="control-label">Your Response:</label>
                  {% render_field answer_form.answer class+="form-control" attr="required":textarea rows="4" %}
                  <br/>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form>
                {% endif %}

              {% else %}
                <h3 align=center><b>Please login to post a response or vote</b></h3>
              {% endif %}

              <hr/>
            </div>
          </div>
        </div>

        {% if Answer %}

          <h4>Responses:</h4>
          {% for ans in Answer %}
            <div style="row">
					    <p class="{% cycle 'leftspeech' 'rightspeech' %} col-xs-12">
                {{ ans.answer | safe }}
					    </p>
					    <div class="col-xs-2 {% cycle '' 'pull-right' %}">
                <img class="img-responsive img-circle" src="{% avatar_url ans.answer_provided_by %}" alt="" />
                <br/>
              </div>
					    <div class="col-xs-10">
                <br/>
                Answered by
                {% if ans.answer_provided_by.userprofile.clinicianprofile %}
                  <span align="{% cycle 'right' 'left' %}" style="color:red;"> Clinician <a href="{% url 'view_doctor' ans.answer_provided_by.userprofile.clinicianprofile.id %}"><b><u>Dr. {{ ans.answer_provided_by.first_name }} {{ ans.answer_provided_by.last_name }}</u></b></a> </span>
                {% else %}
                  <span align="{% cycle 'right' 'left' %}"><b>{{ ans.answer_provided_by.username }}</b> </span>
                {% endif %}
                on <b>{{ ans.timestamp }}</b>
            	</div>
				    </div>
          {% endfor %}

        {% else %}

          <div style="row">
            <br/>
            <br/>
            <h4 align=center>No answers yet.</h4>
          </div>

        {% endif %}

		  </div>
			<div class="col-md-2 col-sm-12">
			</div>

		</div>

{% endblock %}

base/templates/qna/doc_specialty_questions.html
{% extends 'common/common_base.html' %}
{% block title %}
<a href="{% url 'forums' %}">Wassuphealth!
  <span class="sub">Forums</span>
</a>
{% endblock %}
{% block wsh_content %}

  {% load staticfiles %}
  {% load widget_tweaks %}
  {% load avatar_tags %}

    <div class="container">
			<div class="hidden-xs hidden-sm" style="margin-top:50px;"></div>
			<div class="row col-md-12">
				<h1>Wassup Doc!<small> on {{ title }}</small></h1>
			</div>
			<div class="col-md-8 col-sm-12 container">

        {% if qns %}

          <h4 align="left">Answered Questions</h4>

          {% for qn in qns %}

            <div style="row">
              <hr/>
					    <p class="{% cycle 'leftspeech' 'rightspeech' %} col-xs-12">
                <a href="{% url 'get_question' qn.pk %}">{{ qn.question }}</a>
					    </p>
					    <div class="col-xs-2 {% cycle '' 'pull-right' %}">
						    <img class="img-responsive img-circle" src="{% avatar_url qn.posted_by %}" alt="" />
                <br/>
					    </div>
					    <div class="col-xs-10">
                <br/>
                Posted by <b>{{ qn.posted_by.username }}</b> on <b>{{ qn.timestamp }}</b>
					    </div>
				    </div>
          {% endfor %}

        {% else %}
          <br/>
          <br/>
          <h3 align=center>No questions asked yet. Be the first? Towards your right! <span class="glyphicon glyphicon-arrow-right"></span></h3>
        {% endif %}

			</div>
			<div class="col-md-4 col-sm-12 container">
				<div style="row">

          <form action="{% url 'save_question' specialty_id %}" method="POST">
            {% csrf_token %}
						<div class="form-group">
							<h3 align="right">Ask a Question!</h3>
              <br/>
              {% render_field question_form.question class+="form-control" attr="required":textarea rows="4" %}

              <div class="form-group form-inline">
                <br/>
                <p align=center>
                  <label for="private" class="control-label">Ask privately? </label>
                  {% render_field question_form.private class+="form-control" %}
                  &nbsp
                  <label for="tag_profile" class="control-label">Tag profile? </label>
                  {% render_field question_form.tag_profile class+="form-control" %}
                  &nbsp
                  <button type="submit" class="btn btn-default">Submit!</button>
                </p>
                <hr/>
              </div>
						</div>
					</form>
				</div>
				<div style="row">
					<div class="list-group">
						<p class="list-group-item list-group-item-warning">
								Related Specialists
						</p>
            {% for specialist in related_specialists %}
						<a href="{% url 'view_doctor' specialist.id %}" class="list-group-item">Dr. {{ specialist.userprofile.user.first_name }} {{ specialist.userprofile.user.last_name }}</a>
						{% endfor %}
					</div>
				</div>
				<div style="row">
					<div class="list-group">
						<p class="list-group-item list-group-item-warning">
							List of Popular Topics
						</p>
					</div>
				</div>
			</div>
      <div class="row">
        <hr/>
        <p align=justify style="font-size:14px; color:grey"><b>Note:</b> Suggestions offered by doctors on <b>Wassuphealth!</b> are of advisory nature i.e., for educational and informational purposes only. Content posted on, created for, or compiled by <b>Wassuphealth!</b> is not intended or designed to replace your doctor's independent judgment about any symptom, condition, or the appropriateness or risks of a procedure or treatment for a given person.</h5>
      </div>
		</div>

{% endblock %}