wassuphealth/urls.py
from django.conf.urls 					import patterns, include, url
from django.contrib 					import admin
from django.conf.urls.static            import static
from portal 							import views
from django.contrib.staticfiles.urls    import staticfiles_urlpatterns
from postman_attachments.forms          import FullReplyAttachmentForm, FullWriteAttachmentForm
from postman.views                      import *

#wires of the site
urlpatterns = patterns('',
    # Examples:

    # Django-Admin
    url(r'^admin/', include(admin.site.urls), name='django_admin'),

    # Forums - landing and main
    url(r'^forums/$','forums.views.forum_pre_landing', name='view_forums'),
    url(r'^forums/index/$', 'forums.views.main', name='forums'),

    # Community Forums
	url(r'^forums/community/(\d+)/$', 'forums.views.forum', name='forum'),
    url(r'^forums/community/thread/(\d+)/$', 'forums.views.show_thread', name='thread'),
    url(r'^forums/community/reply/(\d+)/$', 'forums.views.reply_to_thread', name='reply'),
    url(r'^forums/community/new_thread/(\d+)/$', 'forums.views.new_thread', name='new_thread'),
    url(r'^forums/community/post/(upvote|downvote)/(\d+)/(\d+)/$', 'forums.views.post_vote', name='post_vote'),

    # Doctors Forums
    url(r'^forums/doc/(\d+)/$', 'QnA.views.show_specialty', name='questions_specialty'),
    url(r'^forums/doc/question/get/(\d+)/$', 'QnA.views.show_specialty_question', name='get_question'),
    url(r'^forums/doc/question/(upvote|downvote)/(\d+)/$', 'QnA.views.question_vote', name='question_vote'),
    url(r'^forums/doc/question/save/(\d+)/$', 'QnA.views.new_question', name='save_question'),
    url(r'^forums/doc/question/answer/save/(\d+)/$', 'QnA.views.save_answer', name='save_answer'),

    # Portal
	url(r'^$','portal.views.home', name='home'),
    url(r'^news/$','portal.views.news', name='news'),
    url(r'^tag/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_tagged_under', name='view_tagged'),
    url(r'^tags/$', 'portal.views.view_all_tags', name='view_all_tags'),
	url(r'^mastercategory/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_master_category', name='view_master_category'),
    url(r'^category/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_category', name='view_category'),
    url(r'^article/(?P<id>\d+)/(?P<slug>[^\.]+)', 'portal.views.view_article', name='view_article'),
    url(r'^conditions/$', 'portal.views.view_all_conditions', name='conditions'),
    url(r'^conditions/view/(?P<id>\d+)/(?P<slug>[^\.]+)', 'portal.views.view_condition', name='view_condition'),

 	# Registration
    url(r'^register/$','registration.views.index', name='registration'),
    url(r'^register/public/$', 'registration.views.register_publicuser', name='publicuser_registration'),
    url(r'^register/clinician/$', 'registration.views.register_clinician', name='clinician_registration'),
    url(r'^register/confirm/(?P<activation_key>\w+)/', 'registration.views.register_confirm'),
    url(r'^account-activated/$','registration.views.account_activated', name='account-activated'),
    url(r'^activation-timeout/$','registration.views.account_timeout', name='account-timeout'),

    # User Authentication
    url(r'^login/$', 'authentication.views.portal_login', name='portal_login'),
    url(r'^login-account/$', 'authentication.views.user_login', name='login'),
	url(r'^logout-account/$', 'authentication.views.user_logout', name='logout'),
    url(r'^account-inactive/$','authentication.views.account_inactive', name='account-inactive'),

    # dashboard
    url(r'^dashboard/$', 'dashboard.views.index', name='dashboard_index'),
    url(r'^dashboard/account/$', 'dashboard.views.edit_profile', name='profile'),
    url(r'^dashboard/healthinfo/$', 'dashboard.views.edit_healthinfo', name='healthinfo'),
    url(r'^dashboard/activities/$', 'dashboard.views.view_user_activities', name='view_activities'),
    url(r'^dashboard/questions/all/$', 'dashboard.views.view_all_activities', name='view_all_activities'),
    url(r'^dashboard/askadoc/save/$', 'dashboard.views.askadoc_save', name='save_doc_form'),
    url(r'^dashboard/commforums/save/$', 'dashboard.views.commforums_save', name='save_comm_form'),
    url(r'^dashboard/professionalinfo/$', 'dashboard.views.edit_clinicianinfo', name='clinicianinfo'),
    url(r'^dashboard/profile/upload/$', 'dashboard.views.profile_avatar_upload', name="profile_avatar"),
    url(r'^dashboard/feedback/$', 'dashboard.views.feedback', name='dfeedback'),
    url(r'^dashboard/feedback/submit/$', 'dashboard.views.submit_feedback', name='d_save_feedback'),
    url(r'^dashboard/appointments/edit/$', 'dashboard.views.edit_appointment', name='edit_appointment'),
    url(r'^dashboard/appointments/delete/$', 'dashboard.views.delete_appointment', name='delete_appointment'),
    url(r'^dashboard/appointments/all/$', 'dashboard.views.get_all_appointments', name='get_all_appointments'),
    url(r'^dashboard/appointments/view/(\d+)/$', 'dashboard.views.view_appointment', name='view_appointment'),

    # dashboard == postman

    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
        WriteView.as_view(form_class=FullWriteAttachmentForm),
        name='pm_write'),

    url(r'^reply/(?P<message_id>[\d]+)/$',
        ReplyView.as_view(form_class=FullReplyAttachmentForm),
        name='pm_reply'),

    url(r'^messages/',include('postman.urls')),

    # dashboard == avatar
    url(r'^avatar/', include('avatar.urls')),

    # comments
    url(r'^comments/', include('django_comments.urls')),

    # appointments
    url(r'^appointments/book/doctor/(\d+)/$', 'appointments.views.book_appointment', name='book_appointment'),
    url(r'^appointments/save/(\d+)/$', 'appointments.views.save_appointment', name='save_appointment'),

    # Profile
    url(r'^doctors/view/(\d+)/$', 'profile.views.view_doctor_profile', name='view_doctor'),
    url(r'^doctors/', 'profile.views.view_doctors', name='doc_dir'),

    # Feedback
    url(r'^feedback/$','feedback.views.index', name='feedback'),
    url(r'^feedback/submit/$','feedback.views.submit_feedback',name='save_feedback'),

    # Static Pages
    url(r'', include('django.contrib.flatpages.urls')),
    url(r'^PDPA/$', 'flatpage', {'url': '/PDPA/'}, name='PDPA'),
	url(r'^about-wassuphealth/$', 'flatpage', {'url': '/about-wassuphealth/'}, name='about-wassuphealth'),
    url(r'^legal/terms-of-use/$', 'flatpage', {'url': '/legal/terms-of-use'}, name='legal-terms-of-use'),
    url(r'^forums/disclaimer/$', 'flatpage', {'url': '/forums/disclaimer/'}, name='forums-disclaimer'),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        # Media Files
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
    )

forums/models.py
# Community Forums

from django.conf                import settings
from django.db 					import models
from profile.models             import User
from model_utils.fields         import StatusField

class Forum(models.Model):

    title = models.CharField(max_length=60)
    def __str__(self):
        return self.title

    def num_posts(self):
        return sum([t.num_posts() for t in self.thread_set.all()])

    def last_post(self):
        if self.thread_set.count():
            last = None
            for t in self.thread_set.all():
                l = t.last_post()
                if l:
                    if not last: last = l
                    elif l.created > last.created: last = l
            return last

class Thread(models.Model):
    title 	= 	models.CharField(max_length=60)
    condition_desc 	= 	models.TextField(blank=True, default="")
    created =	models.DateTimeField(auto_now_add=True)
    creator = 	models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    forum 	= 	models.ForeignKey(Forum)
    upvote      =   models.IntegerField(default=0)
    downvote    =   models.IntegerField(default=0)

    # core information fields - setup core lookup tables for common_scale_options, manage_cost_option, diagnosis_duration_option
    common_scale_options = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
    )

    impact_scale = models.IntegerField(choices = common_scale_options, default=1)
    side_effect_scale = models.IntegerField(choices = common_scale_options, default=1)

    manage_cost_option = (
        (1, 'Not Costly'),
        (2, 'Costly'),
        (3, 'Very Costly'),
    )
    manage_cost = models.IntegerField(choices = manage_cost_option, default=1)

    diagnosis_duration_option = (
        (1, '< 1 Year'),
        (2, '2 - 5 Years'),
        (3, '> 5 Years'),
    )
    diagnosis_duration = models.IntegerField(choices = diagnosis_duration_option, default=1)

    medication = models.TextField(default="")
    experience = models.TextField(default="")

    #def __str__(self):
    #    return self.creator + " - " + self.title

    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count() - 1

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by("created")[0]


class Post(models.Model):
    title 	=	models.CharField(max_length=60)
    created = 	models.DateTimeField(auto_now_add=True)
    creator = 	models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    thread 	= 	models.ForeignKey(Thread)
    body 	=	models.TextField()
    upvote      =  models.IntegerField(default=0)
    downvote    =  models.IntegerField(default=0)

    def __str__(self):
        return "%s - %s - %s" % (self.creator, self.thread, self.title)

    def totalvotes(self):
        return self.upvote + self.downvote

    def short(self):
        return "%s - %s\n%s" % (self.creator, self.title, self.created.strftime("%b %d, %I:%M %p"))
    short.allow_tags = True

forums/forms.py
from forums.models 				import Thread, Post
from django 					import forms

class BaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('auto_id', '%s')
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                field.widget.attrs.update({
                    'placeholder': field.help_text
                })

class QuestionForm(BaseModelForm):
    class Meta:
        model = Thread
        fields = ('condition_desc','impact_scale','side_effect_scale','manage_cost','diagnosis_duration','medication','experience')
        help_texts = {
            'experience':'E.g. It has been too tiring for me to juggle between work and health and has taken a toll on my mental wellbeing',
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(QuestionForm, self).__init__(*args, **kwargs)

class ReplyForm(BaseModelForm):
    class Meta:
        model = Post
        fields = ('body',)
        help_text = {
            'body':'Your answer'
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

forums/views.py
from django.shortcuts 				import get_object_or_404, render, render_to_response
from django.http 					import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers 		import reverse
from django.views 					import generic
from django.utils 					import timezone
from django.core.context_processors import csrf
from django.template 				import RequestContext
from django.contrib.auth            import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator          import Paginator, EmptyPage, PageNotAnInteger
from django.conf 					import settings

from profile.models					import UserProfile
from forums.models					import Forum, Thread, Post
from QnA.models 					import Specialty, Question
from django.contrib.auth.models		import User
from forums.forms 					import QuestionForm, ReplyForm


def forum_pre_landing(request):

	return HttpResponseRedirect('/forums-disclaimer/')

def main(request):

    forums = Forum.objects.order_by('title')
    thread_count = len( Thread.objects.all() )
    question_count = len( Question.objects.all() )
    specialties = Specialty.objects.filter(hot_topic=False).order_by('title')
    hot_topics  = Specialty.objects.filter(hot_topic=True).order_by('title')

    return render(request, 'forums/forums_listing.html', {'forums':forums, 'specialties':specialties, 'hot_topics':hot_topics, 'thread_count':thread_count, 'question_count':question_count})

# Cross Site Request Forgery Protection
def add_csrf(request, ** kwargs):
    d = dict(user=request.user, ** kwargs)
    d.update(csrf(request))
    return d

# Make pagination
def mk_paginator(request, items, num_items):
    """Create and return a paginator."""
    paginator = Paginator(items, num_items)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        items = paginator.page(page)
    except (InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)
    return items

# Returns a list of threads posted under the forum. Speech bubble style
def forum(request, pk):

    """Listing of threads in a forum."""
    question_form = QuestionForm()
    threads = Thread.objects.filter(forum=pk).order_by("created")
    threads = mk_paginator(request, threads, 20)
    title = Forum.objects.get(pk=pk).title

    return render_to_response("forums/forum_thread_list.html", add_csrf(request, title=title, threads=threads, pk=pk, question_form=question_form), RequestContext(request))

# Returns a list of postings under thread
def show_thread(request, thread_id):

	"""Listing of posts in a thread."""
	reply_form = ReplyForm()
	posts = Post.objects.filter(thread=thread_id).order_by("upvote").reverse()
	posts = mk_paginator(request, posts, 15)
	t = Thread.objects.get(pk=thread_id)

	return render_to_response("forums/forum_thread_post.html", add_csrf(request, posts=posts, pk=thread_id, title=t.title, thread = t,
                                                       forum_pk=t.forum.pk, reply_form=reply_form), RequestContext(request))

def increment_post_counter(request):
    profile = request.user.userprofile
    profile.posts += 1
    profile.save()

# for post
def post_vote(request, votetype, thread_id, post_id):

    thread = get_object_or_404(Thread, pk=thread_id)
    post   = get_object_or_404(Post, pk=post_id)

    if votetype == 'upvote':
        post.upvote += 1
        post.save()
    elif votetype == 'downvote':
        post.downvote -= 1
        post.save()

    return HttpResponseRedirect(reverse('forums.views.show_thread', args=[thread.id]))

# submit to system and redirect to the new thread page
@login_required
def new_thread(request, pk):

    """Start a new thread."""
    forum = get_object_or_404(Forum, id=pk)
    question_form = QuestionForm(data=request.POST)

    if request.method == 'POST':

        if question_form.is_valid():

            q = question_form.save(commit=False)
            q.title = ""
            q.forum_id = forum.pk
            q.creator_id = request.user.pk
            q.save()

    return HttpResponseRedirect(reverse("forums.views.show_thread", args=[q.pk]))

@login_required
# Submit to system and redirect to the existing thread page
def reply_to_thread(request, pk):

    thread = get_object_or_404(Thread, id=pk)
    reply_form = ReplyForm(data=request.POST)

    """Reply to a thread."""
    if request.method == 'POST':

        if reply_form.is_valid():

            r = reply_form.save(commit=False)
            r.thread_id = thread.pk
            r.creator_id = request.user.pk
            r.save()

        else:
            print(reply_form.errors)

    return HttpResponseRedirect(reverse("forums.views.show_thread", args=[thread.pk]) + "?page=last")

base/templates/forums/forum_thread_list.html
{% extends 'common/common_base.html' %}
{% block title %}
<a href="{% url 'forums' %}">Wassuphealth!
  <span class="sub">Forums</span>
</a>
{% endblock %}
{% block wsh_content %}

  {% load staticfiles %}
  {% load widget_tweaks %}
  {% load avatar_tags %}

    <div class="container">
			<div class="hidden-xs hidden-sm" style="margin-top:50px;"></div>
			<div class="row col-md-12">
				<h1>Wassup Peeps! <small>on {{ title }}</small></h1>
        <br/>
			</div>
			<div style="row">

				<div class="col-md-8 col-sm-12">

          {% if threads %}
        	<div id="carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#carousel" data-slide-to="0" class="active"></li>
							<li data-target="#carousel" data-slide-to="1"></li>
							<li data-target="#carousel" data-slide-to="2"></li>
						</ol>
						<div class="carousel-inner" role="listbox">
							<div class="item active">
								<img src="{% static 'assets/images/background/bg-footer-3.jpg' %}" alt="...">
								<div class="carousel-caption">
									<h3>{{ title }}</h3>
									<p>Testing Slide</p>
								</div>
							</div>
							<div class="item">
								<img src="{% static 'assets/images/background/bg-footer-3.jpg' %}" alt="...">
								<div class="carousel-caption">
									<h3>{{ title }}</h3>
									<p>Testing Slide</p>
								</div>
							</div>
							<div class="item">
								<img src="{% static 'assets/images/background/bg-footer-3.jpg' %}" alt="...">
								<div class="carousel-caption">
									<h3>{{ title }}</h3>
									<p>Testing Slide</p>
								</div>
							</div>
						</div>

					  <!-- Controls -->
					  <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
						        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						        <span class="sr-only">Previous</span>
					  </a>

					  <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
						        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						        <span class="sr-only">Next</span>
					  </a>

					</div>

          <div class="hidden-xs hidden-sm" style="margin-top:30px;"></div>

          <div class="col-md-12 col-sm-12 container">

            <h3>Discussions</h3>
            <hr/>
            {% for thread in threads.object_list %}
            <div style="row">
    					<p class="{% cycle 'leftspeech' 'rightspeech' %} col-xs-12">
                {{ thread.condition_desc }}
                <br/>
                <a href="{% url 'thread' thread.pk %}">{{ thread.experience }}</a>
                <br/>
    					</p>
    					<div class="col-xs-2 {% cycle '' 'pull-right' %}">
                <img class="img-responsive img-circle" src="{% avatar_url thread.creator %}" alt="" />
                <br/>
              </div>
    					<div class="col-xs-10">
                <br/>
                Replied by
                {% if thread.creator.userprofile.clinicianprofile %}
                  <span class="color:red;"><b>Dr. {{ thread.creator.last_name }} {{ thread.creator.first_name }}</b></span>
                {% else %}
                  <b>{{ thread.creator.username }}</b>
                {% endif %}
                on <b>{{ thread.created }}</b>
    					</div>
    				</div>
            {% endfor %}

    		  </div>
          {% else %}
            <br/>
            <br/>
            <h3 align=center>None has shared their experience yet. Be the first? <br/>Towards your right! <span class="glyphicon glyphicon-arrow-right"></span></h3>
          {% endif %}
        </div>

				<div class="col-md-4 col-sm-12">

          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Share Your Experience</h3>
            </div>
            <div class="panel-body">
              <p>Note: This will be available for public viewing</p>
              <form action="{% url 'new_thread' pk %}" method="POST">
                {% csrf_token %}
                  <div class="form-group">
                    <label class="control-label">What is your diagnosis?</label>
                    {% render_field question_form.condition_desc class="form-control" rows=5 attr="required" %}
                  </div>
      						<div class="form-group">
      							<label for="voting" class="control-label">How does (did) It impact your daily activities?</label>
                    {% render_field question_form.impact_scale id="rating1" class+="rating" attr="required" %}
      						</div>
      						<div class="form-group">
      							<label for="voting" class="control-label">Side effects experienced from medications?</label>
                    {% render_field question_form.side_effect_scale id="rating2" class+="rating" attr="required" %}
      						</div>
      					  <div class="form-group">
      							<label class="control-label">Is it costly to manage?</label><br>
                    {% render_field question_form.manage_cost id="rating3" class+="rating" attr="required" %}
      						</div>
      						<div class="form-group">
      							<label class="control-label">How long have you been diagnosed?</label><br>
                    {% render_field question_form.diagnosis_duration id="rating4" class+="rating" attr="required" %}
      						</div>
      						<div class="form-group">
      							<label for="voting" class="control-label">What medications are you currently on?</label>
                    {% render_field question_form.medication class+="form-control" attr="required" rows="1" cols="50" %}
      						</div>
                  <div class="form-group">
                    <label for="voting" class="control-label">Describe your experience</label>
                    {% render_field question_form.experience class+="form-control" attr="required" rows="5" cols="30" %}
                  </div>
      						<div class="form-group">
      							<div class="col-sm-offset-2 col-sm-2">
      								<button type="submit" class="btn btn-default">Submit Your Experience</button>
                      <br/>
                      <br/>
      							</div>
      						</div>
      				</form>
            </div><!--panel body-->
          </div><!--panel-->
          <div class="row">
            <hr/>
            <p align=justify style="font-size:14px; color:grey"><b>Note:</b> Suggestions offered by doctors on <b>Wassuphealth!</b> are of advisory nature i.e., for educational and informational purposes only. Content posted on, created for, or compiled by <b>Wassuphealth!</b> is not intended or designed to replace your doctor's independent judgment about any symptom, condition, or the appropriateness or risks of a procedure or treatment for a given person.</h5>
          </div>
				</div>

			</div>

			<div class="col-md-4 col-sm-12">
			</div>

		</div>

{% endblock %}

base/templates/forums/forum_thread_post.html
{% extends 'common/common_base.html' %}
{% block title %}
<a href="{% url 'forums' %}">Wassuphealth!
  <span class="sub">Forums</span>
</a>
{% endblock %}
{% block wsh_content %}

  {% load staticfiles %}
  {% load widget_tweaks %}
  {% load avatar_tags %}

    <div class="container">
			<div class="hidden-xs hidden-sm" style="margin-top:100px;"></div>


      <div class="col-md-2 col-sm-12">
			</div>

			<div class="col-md-8 col-sm-12 container">

        <div class="row col-sm-12 col-md-12 container">
          <h3>Condition:</h3>
          <p align=justify>{{ thread.condition_desc }}</p>
          <h3>The Experience:</h3>
          <p align=justify>{{ thread.experience }}</p>
          <p><b>Impact to Daily Life:</b> {{ thread.get_impact_scale_display }} out of 7</p>
          <p><b>Side Effect after Medication:</b> {{ thread.get_side_effect_scale_display }} out of 7</p>
          <p><b>Cost of Managing It:</b> {{ thread.get_manage_cost_display }}</p>
          <p><b>Diagnosed for:</b> {{ thread.diagnosis_duration}} years</p>
          <p align=right><i>Posted by <b>{{ thread.creator.username }}</b> on <b>{{ thread.created }}</b> under <b><a href="{% url 'forum' forum_pk %}">{{ thread.forum.title }}</a></b></i></p>
          <br/>
        </div>

        <div style="row">
          <div class="col-sm-12 col-sm-12 container">
            <div class="form-group">
              {% if user.is_authenticated %}
                <form action="{% url 'reply' pk %}" method="POST">
                  {% csrf_token %}
                  <label for="voting" class="control-label">Your Response:</label>
                  <br/>
                  {% render_field reply_form.body class+="form-control" attr="required":textarea rows="5" %}
                  <br/>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form>
              {% else %}
                <h3 align=center><b>Please login to post a response and vote</b></h3>
              {% endif %}
              <hr/>
            </div>
          </div>
        </div>

        {% for post in posts.object_list %}
        {% if forloop.first %}
          <h4>Most Voted:</h4>
        {% endif %}
        <div style="row">
					<p class="{% cycle 'leftspeech' 'rightspeech' %} col-xs-12">
            {{ post.body }}
					</p>
					<div class="col-xs-2 {% cycle '' 'pull-right' %}">
            <img class="img-responsive img-circle" src="{% avatar_url post.creator %}" alt="" />
            <br/>
          </div>
					<div class="col-xs-10">
            <br/>
            Replied by
            {% if post.creator.userprofile.clinicianprofile %}
              <span align="{% cycle 'right' 'left' %}" class="color:red;"><b>Dr. {{ post.creator.last_name }} {{ post.creator.first_name }}</b></span>
            {% else %}
              <span align="{% cycle 'right' 'left' %}"><b>{{ post.creator.username }}</b></span>
            {% endif %}
            on <b>{{ post.created }}</b>
            {% if user.is_authenticated %}
              <p align=right><a href="{% url 'post_vote' 'upvote' thread.pk post.pk %}"><button type="button" class="btn btn-sm btn-success"><b>This helps!</b> ({{ post.upvote }})</button></a></p>
            {% else %}
              <p align="{% cycle 'right' 'left' %}"><b>This helps! <span class="glyphicon glyphicon-thumbs-up"></span></b> ({{ post.upvote }})</p>
            {% endif %}
					</div>
          <hr/>
				</div>
        {% if forloop.first %}
          <br/>
          <br/>
        {% endif %}
        {% endfor %}

		  </div>
			<div class="col-md-2 col-sm-12">
			</div>

		</div>

{% endblock %}

base/templates/forums/main.html
{% include 'header.html' %}

{% load staticfiles %}
	
	<br/>
	<br/>
	
	<div class="row">
   		
   		<div class="small-12 large-8 columns">

   			<h1 class="article-heading" align=left>Discussion Forums</h1>	
  	 		
  	 	</div>

      {% if user.is_authenticated %}
  	 	<div class="small-12 large-2 columns">
        <br/>
  	 		<a href="#" class="button tiny radius right">Start a Discussion</a>

  	 	</div>

      <div class="small-12 large-2 columns">
        <br/>
        <a href="#" class="button tiny radius right">View Your Topics</a>

      </div>
      {% else %}
      <div class="small-12 large-4 columns">
        <br/>
        <p>Please login to start a topic or post replies</p>
      </div>
      {% endif %}

  	 	<hr/>

  </div>

<!-- Forums  -->
  <div class="row">

    <div class="small-12 large-12 columns">
    
      <table border="0" cellpadding="0" width="100%">
        <tr>
          <td></td>
          <td><h6>Posts</h6></td>
          <td><h6>Last post</h6></td>
          <td></td>
        </tr>

        {% for f in forums %}
        <tr>
          <td {% if forloop.last %}class="last"{% endif %}>
          <div class="title"> <a href="#"><h5>{{ f.title }}</h5></a></div></td>
          <td {% if forloop.last %}class="last"{% endif %}>{{ f.num_posts }}</td>
          <td {% if forloop.last %}class="last"{% endif %}>
              {{ f.last_post.short | linebreaksbr }}</td>
          <td width="5%"{% if forloop.last %}class="last"{% endif %}>
              <a class="button tiny" href="#">View</a>
          </td>
        </tr>

        {% endfor %}
  
      </table>
  
    </div>

  </div>

<br/>

{% include 'footer.html' %}

base/templates/forums/posts.html
{% include 'header.html' %}

{% load staticfiles %}
	
	<br/>
	<br/>
	
	<div class="row">
	<!-- Posts  -->
		<div class="title">{{ title }}</div>
		
			<div id="list">

    		{% for post in posts.object_list %}
        		<div class="post">
            		<span class="title">{{ post.title }}</span><br />
            		by {{ post.creator }} | <span class="date">{{ post.created }}</span> <br /><br />
            		{{ post.body }} <br />
        		</div>
    		{% endfor %}

			</div>

		</div>

	</div>

<!-- Next/Prev page links
    ...
-->

<a class="button" href="{% url forum.views.post 'reply' pk %}">Reply</a>

<br/>

{% include 'footer.html' %}