wassuphealth/urls.py
from django.conf.urls 					import patterns, include, url
from django.contrib 					import admin
from django.conf.urls.static            import static
from portal 							import views
from django.contrib.staticfiles.urls    import staticfiles_urlpatterns
from postman_attachments.forms          import FullReplyAttachmentForm, FullWriteAttachmentForm
from postman.views                      import *

#wires of the site
urlpatterns = patterns('',
    # Examples:

    # Django-Admin
    url(r'^admin/', include(admin.site.urls), name='django_admin'),

    # Forums - landing and main
    url(r'^forums/$','forums.views.forum_pre_landing', name='view_forums'),
    url(r'^forums/index/$', 'forums.views.main', name='forums'),

    # Community Forums
	url(r'^forums/community/(\d+)/$', 'forums.views.forum', name='forum'),
    url(r'^forums/community/thread/(\d+)/$', 'forums.views.show_thread', name='thread'),
    url(r'^forums/community/reply/(\d+)/$', 'forums.views.reply_to_thread', name='reply'),
    url(r'^forums/community/new_thread/(\d+)/$', 'forums.views.new_thread', name='new_thread'),
    url(r'^forums/community/post/(upvote|downvote)/(\d+)/(\d+)/$', 'forums.views.post_vote', name='post_vote'),

    # Doctors Forums
    url(r'^forums/doc/(\d+)/$', 'QnA.views.show_specialty', name='questions_specialty'),
    url(r'^forums/doc/question/get/(\d+)/$', 'QnA.views.show_specialty_question', name='get_question'),
    url(r'^forums/doc/question/(upvote|downvote)/(\d+)/$', 'QnA.views.question_vote', name='question_vote'),
    url(r'^forums/doc/question/save/(\d+)/$', 'QnA.views.new_question', name='save_question'),
    url(r'^forums/doc/question/answer/save/(\d+)/$', 'QnA.views.save_answer', name='save_answer'),

    # Portal
	url(r'^$','portal.views.home', name='home'),
    url(r'^news/$','portal.views.news', name='news'),
    url(r'^tag/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_tagged_under', name='view_tagged'),
    url(r'^tags/$', 'portal.views.view_all_tags', name='view_all_tags'),
	url(r'^mastercategory/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_master_category', name='view_master_category'),
    url(r'^category/(?P<id>\d+)/(?P<slug>[^\.]+)/$', 'portal.views.view_category', name='view_category'),
    url(r'^article/(?P<id>\d+)/(?P<slug>[^\.]+)', 'portal.views.view_article', name='view_article'),
    url(r'^conditions/$', 'portal.views.view_all_conditions', name='conditions'),
    url(r'^conditions/view/(?P<id>\d+)/(?P<slug>[^\.]+)', 'portal.views.view_condition', name='view_condition'),

 	# Registration
    url(r'^register/$','registration.views.index', name='registration'),
    url(r'^register/public/$', 'registration.views.register_publicuser', name='publicuser_registration'),
    url(r'^register/clinician/$', 'registration.views.register_clinician', name='clinician_registration'),
    url(r'^register/confirm/(?P<activation_key>\w+)/', 'registration.views.register_confirm'),
    url(r'^account-activated/$','registration.views.account_activated', name='account-activated'),
    url(r'^activation-timeout/$','registration.views.account_timeout', name='account-timeout'),

    # User Authentication
    url(r'^login/$', 'authentication.views.portal_login', name='portal_login'),
    url(r'^login-account/$', 'authentication.views.user_login', name='login'),
	url(r'^logout-account/$', 'authentication.views.user_logout', name='logout'),
    url(r'^account-inactive/$','authentication.views.account_inactive', name='account-inactive'),

    # dashboard
    url(r'^dashboard/$', 'dashboard.views.index', name='dashboard_index'),
    url(r'^dashboard/account/$', 'dashboard.views.edit_profile', name='profile'),
    url(r'^dashboard/healthinfo/$', 'dashboard.views.edit_healthinfo', name='healthinfo'),
    url(r'^dashboard/activities/$', 'dashboard.views.view_user_activities', name='view_activities'),
    url(r'^dashboard/questions/all/$', 'dashboard.views.view_all_activities', name='view_all_activities'),
    url(r'^dashboard/askadoc/save/$', 'dashboard.views.askadoc_save', name='save_doc_form'),
    url(r'^dashboard/commforums/save/$', 'dashboard.views.commforums_save', name='save_comm_form'),
    url(r'^dashboard/professionalinfo/$', 'dashboard.views.edit_clinicianinfo', name='clinicianinfo'),
    url(r'^dashboard/profile/upload/$', 'dashboard.views.profile_avatar_upload', name="profile_avatar"),
    url(r'^dashboard/feedback/$', 'dashboard.views.feedback', name='dfeedback'),
    url(r'^dashboard/feedback/submit/$', 'dashboard.views.submit_feedback', name='d_save_feedback'),
    url(r'^dashboard/appointments/edit/$', 'dashboard.views.edit_appointment', name='edit_appointment'),
    url(r'^dashboard/appointments/delete/$', 'dashboard.views.delete_appointment', name='delete_appointment'),
    url(r'^dashboard/appointments/all/$', 'dashboard.views.get_all_appointments', name='get_all_appointments'),
    url(r'^dashboard/appointments/view/(\d+)/$', 'dashboard.views.view_appointment', name='view_appointment'),

    # dashboard == postman

    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
        WriteView.as_view(form_class=FullWriteAttachmentForm),
        name='pm_write'),

    url(r'^reply/(?P<message_id>[\d]+)/$',
        ReplyView.as_view(form_class=FullReplyAttachmentForm),
        name='pm_reply'),

    url(r'^messages/',include('postman.urls')),

    # dashboard == avatar
    url(r'^avatar/', include('avatar.urls')),

    # comments
    url(r'^comments/', include('django_comments.urls')),

    # appointments
    url(r'^appointments/book/doctor/(\d+)/$', 'appointments.views.book_appointment', name='book_appointment'),
    url(r'^appointments/save/(\d+)/$', 'appointments.views.save_appointment', name='save_appointment'),

    # Profile
    url(r'^doctors/view/(\d+)/$', 'profile.views.view_doctor_profile', name='view_doctor'),
    url(r'^doctors/', 'profile.views.view_doctors', name='doc_dir'),

    # Feedback
    url(r'^feedback/$','feedback.views.index', name='feedback'),
    url(r'^feedback/submit/$','feedback.views.submit_feedback',name='save_feedback'),

    # Static Pages
    url(r'', include('django.contrib.flatpages.urls')),
    url(r'^PDPA/$', 'flatpage', {'url': '/PDPA/'}, name='PDPA'),
	url(r'^about-wassuphealth/$', 'flatpage', {'url': '/about-wassuphealth/'}, name='about-wassuphealth'),
    url(r'^legal/terms-of-use/$', 'flatpage', {'url': '/legal/terms-of-use'}, name='legal-terms-of-use'),
    url(r'^forums/disclaimer/$', 'flatpage', {'url': '/forums/disclaimer/'}, name='forums-disclaimer'),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        # Media Files
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
    )

profile/models.py
from django.db                  import models
from django.utils               import timezone
from django.utils.http          import urlquote
from django.utils.translation   import ugettext_lazy as _
from django.core.mail           import send_mail
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.conf                import settings

import datetime

class UserManager(BaseUserManager):

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    A fully featured User model with admin-compliant permissions that uses
    a full-length email field as the username.

    Email and password are required. Other fields are optional.
    """
    email       = models.EmailField('Email Address', max_length=254, unique=True, db_index=True)

    username    = models.CharField('User Name', max_length=30, unique=True)

    first_name  = models.CharField('First Name', max_length=30, blank=True)

    last_name   = models.CharField('Last Name', max_length=30, blank=True)

    initial     = models.CharField('Initial', max_length=4, blank=True)

    is_staff    = models.BooleanField('Staff status', default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))

    is_active   = models.BooleanField('Active', default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))

    is_admin    = models.BooleanField(default=False)

    date_joined = models.DateTimeField('Date joined', default=timezone.now)

    objects     = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])


class UserProfile(models.Model):

    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

    activation_key = models.CharField(max_length=40, blank=True)

    key_expires = models.DateTimeField(default=datetime.date.today())

    country = (
        ('SG','Singapore'),
        ('MY','Malaysia'),
        ('ID','Indonesia'),
        ('TH','Thailand'),
        ('IN','India'),
        ('VN','Vietnam'),
        ('KOR','South Korea, Republic of'),
        ('AU','Australia'),
        ('NZ','New Zealand'),
        ('PH','Philippines'),
        ('TW','Taiwan, Republic of China'),
        ('CN','China, People''s Republic of'),
        ('HK','Hong Kong SAR, China'),
        ('MAC','Macau SAR, China')
    )
    country = models.CharField(
        max_length = 4, choices = country, default='SG'
    )

    gender = (
        ('M', 'Female'),
        ('F', 'Male'),
        ('UN', 'Unknown'),
    )

    gender = models.CharField(
        max_length = 2, choices = gender, default='F'
    )

    # The additional attributes we wish to include.

    zip_code = models.CharField(
    	max_length = 6
    )

    birthday = models.DateTimeField(null=True)

    posts = models.IntegerField(default = 0)

    home_address = models.TextField()

    avatar = models.ImageField("Profile Pic", upload_to='avatars/', blank=True, null=True)

    mobile_no = models.CharField(
    	max_length = 20
    )


class Clinic(models.Model):

    # Clinic of Practice
    name = models.CharField('Clinic Name', max_length=254, unique=True)

    # Place of practice e.g. Family Care Clinic
    address = models.TextField()

    # Contact no. of practice
    contact_no = models.CharField(
        max_length = 20
    )

    # Country of practice
    country = models.CharField(
        max_length = 200
    )

    # Website URL of practice
    website = models.URLField('Business Website')

    # Business Email Address for Contact
    business_email_address = models.EmailField('Business Email Address', max_length=254, db_index=True)

    # Place of practice coordinates for use with Google Maps.
    gps_coord = models.CharField(
        max_length = 20
    )

    # Business Registration Date
    business_registered_date = models.DateTimeField('Business Registration Date', null=True)

    # Services in semi-colon delimited fashion
    services = models.TextField('Provided Services')

# User Model for Clinician - with some common features from the UserProfile class
class ClinicianProfile(models.Model):

    """
    - My Education (institutions)(from yyyy - yyyy) provide 3 rows and allow to add *Do It Later*
    - My Medical Training (hospital)(from yyyy - yyyy) provide 3 rows and allow to add *Do It Later*
    """

    userprofile = models.OneToOneField(UserProfile)

    clinic_of_practice = models.ForeignKey(Clinic, default=1)

    specialty_choices = (
        (1, 'Anaethesiology'),
        (2, 'Cardiology'),
        (3, 'Cardiothoracic Surgery'),
        (4, 'Colorectal Surgery'),
        (5, 'Dentistry'),
        (6, 'Dermatology'),
        (7, 'Endocrinology'),
        (8, 'ENT'),
        (9, 'Gastroenterology'),
        (10, 'General Surgery'),
        (11, 'Geriatrics'),
        (12, 'Gynaecology'),
        (13, 'Haematology'),
        (14, 'Hand Surgery'),
        (15, 'Infectious Disease'),
        (16, 'Internal Medicine'),
        (17, 'Oncology'),
        (18, 'Neonatology'),
        (19, 'Neurology'),
        (20, 'Obstetrics'),
        (21, 'Ophthalmology'),
        (22, 'Orthopaedic Surgery'),
        (23, 'Paediatric'),
        (24, 'Paediatric Surgery'),
        (25, 'Plastic Surgery'),
        (26, 'Psychiatry'),
        (27, 'Renal Medicine'),
        (28, 'Respiratory Medicine'),
        (29, 'Rheumatology'),
        (30, 'Urology')
    )

    medical_careergrade_choices = (
        (1, 'Medical Officer'),
        (2, 'Senior Medical Officer'),
        (3, 'Registrar'),
        (4, 'Associate Consultant'),
        (5, 'Consultant'),
        (6, 'Senior Consultant'),
        (7, 'Family Physician'),
        (8, 'Family Physician Associate Consultant'),
        (9, 'Family Physician Consultant'),
        (10, 'Family Physician Senior Consultant'),
        (11, 'Resident'),
        (12, 'Senior Resident'),
        (13, 'Principal Resident')
    )

    # Professional License
    # for SG: SMC MCR Number
    medical_reg_no = models.CharField(
        max_length = 9
    )

    registered_date = models.DateTimeField(null=True)

    clinical_specialty = models.IntegerField(choices = specialty_choices, default=1)

    medical_careergrade = models.IntegerField(choices = medical_careergrade_choices, default=1)

    # Graduate School
    grad_school = models.CharField(
        max_length = 200
    )

    grad_year = models.CharField(
        max_length = 4
    )

    degree_type = models.CharField(
        max_length = 7
    )

    years_of_practice = models.IntegerField(default=0)

    # Free Text Fields
    # text profile of clinician - about me
    medical_interests = models.TextField(default="")
    writeup_text = models.TextField(default="")
    medical_memberships = models.TextField(default="")
    publications = models.TextField(default="")
    affiliations = models.TextField(default="")
    awards = models.TextField(default="")

# User Model for User - with some common features from the UserProfile class
class PublicUserProfile(models.Model):

    #More to be added. E.g. various medical related data
    userprofile = models.OneToOneField(UserProfile)

    race = models.CharField(max_length=100, default="")

    sexual_history_options = ((1, 'Not Sexually Active'),(2, 'Homosexual'),(3, 'Heterosexual'),(4, 'Bisexual'))
    sexual_history = models.IntegerField(choices = sexual_history_options, default=1)

    current_medical_conditions = models.TextField(default="")

    lactose_intolerant_options = ((1,'Yes'),(2,'No'))
    lactose_intolerant = models.IntegerField(choices = lactose_intolerant_options, default=1)

    smoking_options = ((1,'Yes'),(2,'No'))
    smoking = models.IntegerField(choices = smoking_options, default=1)
    smoking_packs = models.CharField(max_length = 4, default=0)
    smoking_years = models.CharField(max_length = 4, default=0)

    alcohol_intake_options = ((1, 'None'),(2,'<7 drinks a week'),(3,'8-14 drinks a week'),(4,'>15 drinks a week'))
    alcohol_intake = models.IntegerField(choices = alcohol_intake_options, default=1)

profile/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from profile.models import User

class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = User
        fields = ("email",)

class CustomUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    
    def __init__(self, *args, **kargs):
        super(CustomUserChangeForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = User
        fields = ("email","username","first_name","last_name","initial","is_staff",)

base/templates/profile/doc_dir.html
{% extends 'common/common_base.html' %} {% load staticfiles %} {% block title %} {% load avatar_tags %}
<a href="{% url 'doc_dir' %}">Wassuphealth!
  <span class="sub">Doctor Directory</span>
</a> {% endblock %} {% block wsh_content %}
<div class="container">

  <div class="hidden-xs hidden-sm" style="margin-top:70px;"></div>
  <div class="row">

    <div class="col-md-9">
      <h2>Viewing All Doctors
        <span class="glyphicon glyphicon-sunglasses"></span>
      </h2>
    </div>

  </div>
  <br/>
  <div class="col-md-9 col-xs-12 col-sm-12">

    <!-- Clinician profile summary-->
    {% for clinician in clinicians %}
    <div class="row">
      <div class="col-md-2" style="padding:10px;">
        <div class="image">
          <img class="img-responsive img-circle" src="{% avatar_url clinician.userprofile.user 70 %}" alt="" />
          <button type="button" class="btn btn-link btn-sm"><a href="{% url 'postman_write' clinician.userprofile.user.email %}">Message</a></button>
        </div>
      </div>
      <div class="col-md-10">
        <!--<h3 class="title"><strong>Dr. {{ user_details.first_name }} {{ user_details.last_name }}</strong></h3>-->
        <h3 class="title">
          <strong>Dr. {{ clinician.userprofile.user.first_name }} {{ clinician.userprofile.user.last_name }} <small>{{ clinician.get_medical_careergrade_display }}</small> </strong>
        </h3>
        <p style="font-size:12px;">{{ clinician.degree_type }}, {{ clinician.grad_school }} {{ clinician.grad_year }}</p>
        <p align=justify>
          <b>About</b>
          <br/>
          {{ clinician.writeup_text | safe }}
        </p>
        <p>
          <b>Clinic</b>
          <br/>{{ clinician.clinic_of_practice.name }}, {{ clinician.clinic_of_practice.address }}
        </p>
        <p align=justify>
          <b>Specialty</b>
          <br/> {{ clinician.get_clinical_specialty_display }}
          <br/>
        </p>
        <p align=justify>
          <b>Medical Interests</b>
          <br/>{{ clinician.medical_interests }}
          <br/>
        </p>
        <p>
          <a href="{% url 'view_doctor' clinician.id %}"><button type="button" class="btn btn-info btn-sm">View More...</button></a>
          <a href="{% url 'book_appointment' clinician.id %}"><button type="button" class="btn btn-primary btn-sm">Book An Appointment</button></a>
        </p>
      </div>
    </div>
    <hr/>
    <!--end of clinician profile summary-->
    {% endfor %}
  </div>
  <div class="col-md-3 col-xs-12 col-sm-12">
    <div class="form-inline">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Search">
      &nbsp
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
    </div>
    <br/>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Popular Doctors</h3>
      </div>
      <div class="panel-body">
        Dr. Tan Ser Kiat, SGH
        <br/> Dr. Chong Tuck Hwa, GP
        <br/> Dr. Ernest Chin, NUHS
        <br/> Dr. Li Jianmin, JHS
      </div>
    </div>
    <br/>
    <h4>Browse by Specialty</h4>
    <hr/> Family Medicine
    <br/> Geriatrics
    <br/> Gynaecology & Obstetrics
    <br/>

  </div>

</div>
{% endblock %}

base/templates/profile/doc_profile_2.html
{% extends 'common/common_base.html' %} {% load staticfiles %} {% block title %} {% load comments %} {% load widget_tweaks %} {% load profile_tags %} {% load avatar_tags %}
<a href="{% url 'doc_dir' %}">Wassuphealth!
  <span class="sub">Doctor Profile</span>
</a> {% endblock %} {% block wsh_content %}
<div class="container">

  <div class="hidden-xs hidden-sm" style="margin-top:100px;"></div>
  <div class="row">
    <!-- Boxes de Acoes -->
    <div class="col-xs-12 col-sm-12">
      <div class="share">
        <span class="fa fa-4x fa-share-alt-square"></span>
      </div>
      <div class="box">
        <div class="icon">
          <div class="image">
            <img class="img-responsive img-circle" src="{% avatar_url user_details 200 %}" alt="" />
          </div>
          <div class="info">
            <h3 class="title">
              <strong>Dr. {{ user_details.first_name }} {{ user_details.last_name }}</strong>
            </h3>
            <h3 class="subtitle">{{ clinician_profile.get_medical_careergrade_display }}, {{ clinician_profile.get_clinical_specialty_display }}</h3>
            <h3 class="subinfo"><a href="{{ clinician_profile.clinic_of_practice.website }}">{{ clinician_profile.clinic_of_practice.name }}</a>
              <br/>N Years of Experience</h3>
            <hr/>
            <p>
              {{ clinician_profile.writeup_text | safe }}
            </p>
            <hr/>
            <br/>
            <div class="information row">
              <div class="col-md-4 col-sm-6">
                <dl>
                  <dt>Education</dt>
                  <dd>{{ clinician_profile.degree_type }}, {{ clinician_profile.grad_school }}</dd>
                </dl>
              </div>
              <div class="col-md-4 col-sm-6">
                <dl>
                  <dt>Medical Membership</dt>
                  <dd>{{ clinician_profile.medical_memberships | safe }}</dd>
                </dl>
              </div>
              <div class="col-md-4 col-sm-6">
                <dl>
                  <dt>Medical Training</dt>
                  <dd>Some Medical School too!</dd>
                </dl>
              </div>
              <div class="col-md-4 col-sm-6">
                <dl>
                  <dt>Publications</dt>
                  <dd>{{ clinician_profile.publications }}</dd>
                </dl>
              </div>
              <div class="col-md-4 col-sm-6">
                <dl>
                  <dt>Affiliations</dt>
                  <dd>{{ clinician_profile.affiliations }}</dd>
                </dl>
              </div>
              <div class="col-md-4 col-sm-6">
                <dl>
                  <dt>Awards</dt>
                  <dd>{{ clinician_profile.awards }}</dd>
                </dl>
              </div>
            </div>
            <div class="more">
              <a href="{% url 'book_appointment' clinician_profile.id %}" title="Title Link">
                Book an appointment with this doctor! <i class="fa fa-angle-double-right"></i>
              </a> &nbsp
              <a href="#" title="Title Link">
                Thank this Doctor! <i class="fa fa-angle-double-right"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="space"></div>
      </div>

      <!--Comments-->

      <div class="row">
        <div class="col-xs-12 col-md-8">

          {% get_comment_count for clinician_profile as comment_count %}
          <h3>What people have to say on Dr. {{ user_details.first_name }} {{ user_details.last_name }}.
            <small>{{ comment_count }} comments</small>
          </h3>

          <br/>

          {% get_comment_list for clinician_profile as clinician_comments %}
          {% for c in clinician_comments %}
          <div class="row">
            <h4>Rated {{ c.rating }}/5 &nbsp<small>{{ c.submit_date }} by <b>By {{ c.user_name }}</b></small></h4>
            <p style="font-size:16px;">{{ c.comment }}</p>
            <hr/>
          </div>
          {% endfor %}

        </div>
        <div class="col-xs-12 col-md-4">
          <h3>Write a comment</h3>
          <hr/> {% if user.is_authenticated %} {% get_comment_form for clinician_profile as form %}
          <div class="form-container">
            <form action="{% comment_form_target %}" method="POST">
              {% csrf_token %}
              <label for="comment">Comments</label>
              {% render_field form.comment class+="form-control" rows=5 placeholder="Comments here..." %}
              {% render_field form.honeypot class+="form-control" style="display:none;" %}
              {{ form.content_type }} {{ form.object_pk }} {{ form.timestamp }} {{ form.security_hash }}
              <br/>
              <input type="hidden" name="next" value="{% url 'view_doctor' clinician_profile.id %}" />
              <div class="form-group form-inline">
                <label for="rating">Rating</label>
                {% render_field form.rating class+="form-control" placeholder="Rating" %}
              </div>
              <button type="submit" id="id_submit" class="btn btn-primary">Add comment</button>
            </form>
          </div>
          {% else %}
          <p>Please login to leave a comment</p>
          {% endif %}
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}